/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
	export interface Resource {
		Database: {
			clusterArn: string;
			database: string;
			host: string;
			password: string;
			port: number;
			reader: string;
			secretArn: string;
			type: "sst.aws.Aurora";
			username: string;
		};
		DatabaseMigrator: {
			name: string;
			type: "sst.aws.Function";
		};
		Server: {
			service: string;
			type: "sst.aws.Service";
			url: string;
		};
		Vpc: {
			type: "sst.aws.Vpc";
		};
	}
}
/// <reference path="sst-env.d.ts" />

import "sst";
